title: "3dots..."
description: Random thoughts on everything.
author: Dušan Maďar

domain: dusanmadar.github.io
url: "https://dusanmadar.github.io/"


markdown: kramdown
theme: minima
minima:
  date_format: "%Y-%m-%d"
