version: '3.8'

services:
  jekyll:
    image: jekyll/jekyll:pages
    # command: jekyll serve --watch --force_polling
    command: tail -f /dev/null
    ports:
      - 4000:4000
    volumes:
      - ./src:/srv/jekyll
